### ISSUE TITLE
assert

### ISSUE THREAD

**Issue by folkertvanheusden** [nathankjer/instruments#1]
Hi,

I had to change "get_waveform_samples" a bit or else it would often fail on the 

    assert len(buff) == points

(line 2710 of instruments.py).

```
        self.set_waveform_stop(1200)

        while True:
            tmp_buff = self.get_waveform_data()
            n_header_bytes = int(chr(tmp_buff[1])) + 2
            n_data_bytes = int(tmp_buff[2:n_header_bytes].decode("ascii"))
            buff = tmp_buff[n_header_bytes : n_header_bytes + n_data_bytes]
            if len(buff) == 1200:
                break

        samples = list(struct.unpack(str(len(buff)) + "B", buff))
```

I also noticed that there's a "set_waveform_format('WORD')". Would that increase the precision of the measured samples? And will that work with get_waveform_samples?

**Comment by nathankjer** [comment]
@folkertvanheusden this issue should be resolved now. Sorry it took so long to get to it. I sold my instruments a while back and just recently got new ones. Thanks for the feedback!
